/// The supported parameter and return-value types for a Flutter
/// [AppFunctionDefinition]. Mirrors the scalar types supported by
/// `androidx.appfunctions.AppFunctionData`.
enum AppFunctionDataType {
  /// UTF-8 string value.
  string,

  /// 64-bit signed integer value.
  int64,

  /// 64-bit IEEE-754 double value.
  double,

  /// Boolean value.
  bool,

  /// Ordered list of UTF-8 strings.
  stringList;

  /// Wire-format identifier used in the Dart↔Kotlin protocol.
  String get wireName => switch (this) {
        AppFunctionDataType.string => 'string',
        AppFunctionDataType.int64 => 'int64',
        AppFunctionDataType.double => 'double',
        AppFunctionDataType.bool => 'bool',
        AppFunctionDataType.stringList => 'stringList',
      };

  /// Returns the [AppFunctionDataType] for the given [wireName], or `null`
  /// if no such type exists.
  static AppFunctionDataType? fromWireName(String? wireName) {
    if (wireName == null) return null;
    for (final t in AppFunctionDataType.values) {
      if (t.wireName == wireName) return t;
    }
    return null;
  }
}

/// Describes a single parameter of an [AppFunctionDefinition].
///
/// The [type] and (optional) [enumValues] are mirrored in the catalog
/// generated by the `appfunctions` KSP processor on the Android side.
class AppFunctionParameter {
  /// The name of the parameter. Must match the key used by the agent in
  /// the `parameters` `AppFunctionData` payload.
  final String name;

  /// KDoc-style description of the parameter. Surfaced to the agent.
  final String description;

  /// Scalar type of the parameter.
  final AppFunctionDataType type;

  /// Whether the parameter must be supplied. Defaults to `true`.
  final bool required;

  /// When [type] is [AppFunctionDataType.string], restricts the accepted
  /// values to this list. Mirrors
  /// `@AppFunctionStringValueConstraint(enumValues = [...])`.
  final List<String> enumValues;

  const AppFunctionParameter({
    required this.name,
    this.description = '',
    this.type = AppFunctionDataType.string,
    this.required = true,
    this.enumValues = const [],
  });

  /// A required UTF-8 string parameter.
  factory AppFunctionParameter.string(
    String name, {
    String description = '',
    bool required = true,
    List<String> enumValues = const [],
  }) =>
      AppFunctionParameter(
        name: name,
        description: description,
        type: AppFunctionDataType.string,
        required: required,
        enumValues: enumValues,
      );

  /// An optional UTF-8 string parameter.
  factory AppFunctionParameter.optionalString(
    String name, {
    String description = '',
  }) =>
      AppFunctionParameter(
        name: name,
        description: description,
        type: AppFunctionDataType.string,
        required: false,
      );

  /// A required 64-bit signed integer parameter.
  factory AppFunctionParameter.int(
    String name, {
    String description = '',
    bool required = true,
  }) =>
      AppFunctionParameter(
        name: name,
        description: description,
        type: AppFunctionDataType.int64,
        required: required,
      );

  /// A required IEEE-754 double parameter.
  factory AppFunctionParameter.double(
    String name, {
    String description = '',
    bool required = true,
  }) =>
      AppFunctionParameter(
        name: name,
        description: description,
        type: AppFunctionDataType.double,
        required: required,
      );

  /// A required boolean parameter.
  factory AppFunctionParameter.bool(
    String name, {
    String description = '',
    bool required = true,
  }) =>
      AppFunctionParameter(
        name: name,
        description: description,
        type: AppFunctionDataType.bool,
        required: required,
      );

  /// A required list of UTF-8 strings parameter.
  factory AppFunctionParameter.stringList(
    String name, {
    String description = '',
    bool required = true,
  }) =>
      AppFunctionParameter(
        name: name,
        description: description,
        type: AppFunctionDataType.stringList,
        required: required,
      );

  /// Serialises this parameter to a JSON-compatible map. The Android
  /// bridge deserialises this map to validate incoming `AppFunctionData`
  /// payloads.
  Map<String, dynamic> toJson() => <String, dynamic>{
        'name': name,
        'description': description,
        'type': type.wireName,
        'required': required,
        if (enumValues.isNotEmpty) 'enumValues': enumValues,
      };

  @override
  String toString() =>
      'AppFunctionParameter($name: ${type.wireName}, required=$required)';
}
